apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-operator
  label:
    app: kafka-operator
    approle: operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: kafka-operator-rolebinding
  label:
    app: kafka-operator
    approle: operator
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kafka-operator
