apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.dnsName }}
  labels:
    app: {{ .Values.applicationName }}
    component: zookeeper
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    chart:  {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  ports:
  - port: 2888
    name: peer
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: {{ .Values.applicationName }}
    component: zookeeper
    release: {{ .Release.Name }}

