apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.dnsName }}
  labels:
    component: zookeeper
    {{- include "standardLabels" . | indent 4 }}
spec:
  ports:
  - port: 2888
    name: peer
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: {{ .Values.applicationName }}
    component: zookeeper
    release: {{ .Release.Name }}

