apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.serviceName }}
  labels:
    component: zookeeper
    {{- include "standardLabels" . | indent 4 }}
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: {{ .Values.applicationName }}
    component: zookeeper
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    chart:  {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
